

<?php
/** Copyright 2012 Hochschule Luzern - Technik & Architektur 
 *
 * Provides access to the TIP guestbook table in the MySQL database.
 * Supports listing of all guestbok items, inserting new items and removing 
 * an exiting item.    
 * @author Peter Sollberger <peter.sollberger@hslu.ch>
 */
class GuestbookAccess
{
    private $db;
    
    /**
     * Opens the database.
     */
    public function __construct()
    {
        $username = "root";
        $password = "";
        $database = "mydb";
        
        // Open the database
        $this->db = new mysqli("localhost", $username, $password, $database);        
        if ($this->db == false) {
            die("Unable to connect to database");
        }
    }
    
    /**
     * Closes the database.
     */
    public function __destruct()
    {
        $this->db->close();
    }
    
    /**
     * Return in an table (two-dimensional array) all entries of the guest book.
     * Each row of the table represents one entry in the guest book.
     * @return table[...]["Index"]   --> Integer: Index of the entry (for deleting)
     *         table[...]["Name"]    --> String: name of the user
     *         table[...]["eMail"]   --> String: e-Mail of the user
     *         table[...]["Comment"] --> String: The guest book entry (as text)
     *         table[...]["Date"]    --> String: Date and time of the entry
     */
    public function getEntries()
    {

        $sql = "SELECT * FROM myguests";
 
        $db_erg = mysqli_query( $this->db, $sql );
        if ( ! $db_erg )
        {
        die('Ungültige Abfrage: ' . mysqli_error());
        }
        
        echo '<table border="1">';
        while ($zeile = mysqli_fetch_array($db_erg))
        {
        echo "<tr>";
        echo "<td>". $zeile['firstname'] . "</td>";
        echo "<td>". $zeile['email'] . "</td>";
        echo "<td>". $zeile['comment'] . "</td>";
        echo "</tr>";
        }
        echo "</table>";
        
        mysqli_free_result( $db_erg );
    }
    
    /**
     * Evaluates current time and adds a new guestbook entry with given name, 
     * e-Mail and comment.
     * @param String $name    User name
     * @param String $eMail   User e-mail address
     * @param String $comment The entry text
     * @return On success: Integer Index generated by the database for the entry
     *         On failure: Boolean false
     */
    function addEntry($name, $eMail, $comment)
    {   
        // Add entry to the database
        $sql = "INSERT INTO `myguests` (`id`, `firstname`, `comment`, `email`) VALUES (NULL, '$name', '$comment', '$eMail')";

        if ($this->db->query($sql) === TRUE) {
            echo "New record created successfully";
        } else {
            echo "Error: " . $sql . "<br>" . $conn->error;
        }

    }
    
    /**
     * Return in an lis(one-dimensional array) all data of one guest book entry.
     * @return list["Index"]   --> Integer: Index of the entry (for deleting)
     *         list["Name"]    --> String: name of the user
     *         list["eMail"]   --> String: e-Mail of the user
     *         list["Comment"] --> String: The guest book entry (as text)
     *         list["Date"]    --> String: Date and time of the entry
     */
    public function getEntry($index)
    {
        // For security: supress SQL injection
        settype($index, 'Integer');

        // Make querry
        $result = mysql_query("SELECT * FROM guestbook WHERE indes = '$index'");
        
        $list = false;
        $row = mysql_fetch_array($result);
        if ($row != false) {            
            $list["Index"]   = $row["indes"];
            $list["Date"]    = $row["date"];
            $list["Name"]    = $row["name"];
            $list["eMail"]   = $row["email"];
            $list["Comment"] = $row["comment"];
        }
        
        mysql_free_result($result);
        
        return $list;
    }
}

?>

